/**
 * FHIR R4 Value Sets for DocumentReference
 *
 * Enumerations derived from FHIR R4 value sets used by the DocumentReference resource.
 *
 * @see https://hl7.org/fhir/R4/documentreference.html
 */

/**
 * The status of the document reference.
 * @see https://hl7.org/fhir/R4/valueset-document-reference-status.html
 */
export enum DocumentReferenceStatus {
    /** This is the current reference for this document */
    Current = 'current',
    /** This reference has been superseded by another reference */
    Superseded = 'superseded',
    /** This reference was created in error */
    EnteredInError = 'entered-in-error',
}

/**
 * Status of the underlying document.
 * @see https://hl7.org/fhir/R4/valueset-composition-status.html
 */
export enum DocumentReferenceDocStatus {
    /** This is a preliminary composition or document */
    Preliminary = 'preliminary',
    /** This version of the composition is complete */
    Final = 'final',
    /** The composition content has been amended */
    Amended = 'amended',
    /** The composition or document was originally created/issued in error */
    EnteredInError = 'entered-in-error',
}

/**
 * The type of relationship between documents.
 * @see https://hl7.org/fhir/R4/valueset-document-relationship-type.html
 */
export enum DocumentRelationshipType {
    /** This document logically replaces or supersedes the target document */
    Replaces = 'replaces',
    /** This document was generated by transforming the target document */
    Transforms = 'transforms',
    /** This document is a signature of the target document */
    Signs = 'signs',
    /** This document adds additional information to the target document */
    Appends = 'appends',
}
