from enum import StrEnum


class DocumentReviewStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REVIEW_IN_PROGRESS = "REVIEW_IN_PROGRESS"
    REJECTED = "REJECTED"
    REJECTED_DUPLICATE = "REJECTED_DUPLICATE"
    REASSIGNED = "REASSIGNED"
    REASSIGNED_PATIENT_UNKNOWN = "REASSIGNED_PATIENT_UNKNOWN"
    NEVER_REVIEWED = "NEVER_REVIEWED"
    REVIEW_PENDING_UPLOAD = "REVIEW_PENDING_UPLOAD"
    VIRUS_SCAN_FAILED = "VIRUS_SCAN_FAILED"

