from enum import StrEnum


class DocumentReviewStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    APPROVED_PENDING_DOCUMENTS = "APPROVED_PENDING_DOCUMENTS"
    REJECTED = "REJECTED"
    REJECTED_DUPLICATE = "REJECTED_DUPLICATE"
    REASSIGNED = "REASSIGNED"
    REASSIGNED_PATIENT_UNKNOWN = "REASSIGNED_PATIENT_UNKNOWN"
    NEVER_REVIEWED = "NEVER_REVIEWED"
    REVIEW_PENDING_UPLOAD = "REVIEW_PENDING_UPLOAD"
    VIRUS_SCAN_FAILED = "VIRUS_SCAN_FAILED"


class DocumentReviewReason(StrEnum):
    REVIEW_FROM_DATA_CONTROLLER = "Needs review from data controller"
