from enum import Enum


class LoggingAppInteraction(Enum):
    LOGIN = "Login"
    EDGE_PRESIGN = "CloudFront Edge Presign"
    PATIENT_SEARCH = "Patient search"
    VIEW_PATIENT = "View Patient"
    VIEW_LG_RECORD = "View LG record"
    DOWNLOAD_RECORD = "Download a record"
    DELETE_RECORD = "Delete a record"
    FHIR_DELETE_RECORD = "Delete a FHIR record"
    GET_DOCUMENT = "Get document reference"
    UPLOAD_RECORD = "Upload a record"
    UPDATE_RECORD = "Update a record"
    STITCH_RECORD = "Stitch a record"
    ODS_REPORT = "Download an ODS report"
    LOGOUT = "Logout"
    SEND_FEEDBACK = "Send feedback"
    FEATURE_FLAGS = "Feature flags"
    VIRUS_SCAN = "Virus Scan"
    UPLOAD_CONFIRMATION = "Upload confirmation"
    UPDATE_UPLOAD_STATE = "Update upload state"
    GET_REVIEW_DOCUMENTS = "Get review documents"
    POST_REVIEW_DOCUMENTS = "Create review documents"
    SEARCH_REVIEW_DOCUMENTS = "Search review documents"
    SEARCH_DOCUMENT = "Search document reference"
    CHECK_REVIEW_STATUS = "Check review document status"
    SSH_KEY_MANAGEMENT = "SSH Key Management"
    UPDATE_REVIEW = "Update review"
    ACCESS_AUDIT = "Access audit"
    BULK_UPLOAD = "Bulk upload"
    MANIFEST_JOB = "Manifest job"
    SEARCH_HISTORY = "Search document reference history"
