export enum routes {
    home = '/home',
    patientSearch = '/patient/search',
    patientVerify = '/patient/verify',
    createReport = '/create-report',
    createReportComplete = '/create-report/complete',
    patientDocuments = '/patient/documents',
    patientDocumentsDelete = '/patient/documents/delete',
    documentView = '/patient/documents/view',
    documentVersionHistory = '/patient/documents/version-history',
    restoreConfirm = '/patient/documents/restore-confirm',
    restoreUploading = '/patient/documents/restore-uploading',
    restoreComplete = '/patient/documents/restore-complete',
    sessionExpired = '/session-expired',
    documentUpload = '/patient/document-upload',
}
