name: "Z-AUTOMATED: PR Checklist validator"

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read # Required for anchore/sbom-action
  pull-requests: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Run checklist validator
        uses: ./.github/actions/checklist_validator
        with:
          body: ${{ github.event.pull_request.body }}
