name: "Z-BASE E2E Test: E2E shared actions for running Core FHIR API E2E tests on the NDR Backend"

run-name: "${{ github.event.inputs.build_branch }} | ${{ github.event.inputs.environment }} | ${{ github.event.inputs.sandbox }}"

on:
  workflow_call:
    inputs:
      build_branch:
        description: "Branch with e2e tests."
        required: true
        type: "string"
      environment:
        description: "Which Environment type are we using"
        required: true
        type: "string"
      sandbox:
        description: "Sandbox to run the smoke tests on."
        required: true
        type: "string"
    secrets:
      AWS_ASSUME_ROLE:
        required: true

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  core-fhir-api-e2e-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      environment: ${{ inputs.environment }}
      sandbox: ${{ inputs.sandbox }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: "NHSDigital/national-document-repository"
          ref: ${{ inputs.build_branch }}

      - name: AWS Role
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-skip-session-tagging: true
          mask-aws-account-id: true
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Make virtual environment
        run: |
          make env

      - name: Start virtual environment
        run: |
          source ./lambdas/venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Run Core FHIR API E2E tests
        run: make test-core-fhir-api-e2e WORKSPACE=${{ inputs.sandbox }}
