name: "Z-BASE E2e Test: MNS E2E Tests"

on:
  workflow_call:
    inputs:
      build_branch:
        description: "Branch with e2e tests."
        required: true
        type: "string"
      environment:
        description: "Which Environment type are we using"
        required: true
        type: "string"
      sandbox:
        description: "Sandbox to run the smoke tests on."
        required: true
        type: "string"
    secrets:
      AWS_ASSUME_ROLE:
        required: true

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  mns-e2e-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        test-file:
          - test_mns_process.py
          - test_mns_death.py
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: "NHSDigital/national-document-repository"
          ref: ${{ inputs.build_branch }}

      - name: AWS Role
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-skip-session-tagging: true
          mask-aws-account-id: true
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Make virtual environment
        run: |
          make env

      - name: Start virtual environment
        run: |
          source ./lambdas/venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV


      - name: Set E2e Test Variables
        run: |
          AWS_WORKSPACE="${SANDBOX}"
          AWS_DEFAULT_REGION=${{ vars.AWS_REGION }}
          echo "AWS_WORKSPACE=$AWS_WORKSPACE" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> $GITHUB_ENV
        env:
          SANDBOX: ${{ inputs.sandbox }}

      - name: Run MNS E2E Test - ${{ matrix.test-file }}
        run: |
          cd ./lambdas && ./venv/bin/python3 -m pytest tests/e2e/mns/${{ matrix.test-file }} -vv
