name: "Deploy: Dev"

run-name: "${{ github.event.inputs.git_ref }} | ${{ github.event.inputs.sandbox_name }}"

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: "Branch, tag or SHA to deploy"
        required: true
        type: "string"
        default: "main"
      sandbox_name:
        description: "Which Sandbox to push to."
        required: true
        type: "string"
      bulk_upload:
        description: "Disable the PDS stub and run a Bulk Upload on this sandbox?"
        required: true
        type: boolean
      mock_login_enabled:
        description: "Deploy with mock login enabled?"
        type: boolean
        required: true
  push:
    branches:
      - PRM-516

permissions:
  actions: read # Required for anchore/sbom-action
  contents: write # Required for anchore/sbom-action
  pull-requests: write
  id-token: write

jobs:
  lambda_test_job:
    name: Run Lambda Unit Tests
    uses: ./.github/workflows/base-lambdas-reusable-test.yml
    with:
      python_version: "3.11"
      git_ref: ${{ inputs.git_ref }}

  react_testing_job:
    name: Run UI Unit Tests
    uses: ./.github/workflows/base-vitest-test.yml
    with:
      git_ref: ${{ inputs.git_ref }}

  cypress_build_job:
    name: Build UI version for E2E Tests
    uses: ./.github/workflows/base-cypress-build.yml
    with:
      git_ref: ${{ inputs.git_ref }}

  cypress_test_job:
    name: Run Cypress E2E Tests
    needs: [cypress_build_job]
    uses: ./.github/workflows/base-cypress-test-all-env.yml
    with:
      cypress_base_url: ${{ vars.CYPRESS_BASE_URL }}
      git_ref: ${{ inputs.git_ref }}

  publish_all_lambda_layers:
    name: Publish all Lambda Layers
    uses: ./.github/workflows/base-lambda-layer-reusable-publish-all.yml
    with:
      git_ref: ${{ inputs.git_ref }}
      sandbox: ${{ inputs.sandbox_name }}
      python_version: "3.11"
      environment: "development"
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  deploy_all_lambdas:
    name: Deploy all Lambdas
    uses: ./.github/workflows/base-lambdas-reusable-deploy-all.yml
    needs: ["publish_all_lambda_layers"]
    with:
      environment: "development"
      git_ref: ${{ inputs.git_ref }}
      sandbox: ${{ inputs.sandbox_name }}
      python_version: "3.11"
      is_sandbox: true
      mock_login_enabled: ${{ inputs.mock_login_enabled }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  deploy_ui:
    name: Deploy UI
    uses: ./.github/workflows/base-deploy-ui.yml
    with:
      environment: "development"
      git_ref: ${{ inputs.git_ref }}
      sandbox: ${{ inputs.sandbox_name }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  bulk_upload:
    name: "Run Bulk Upload"
    if: ${{ inputs.bulk_upload }}
    uses: "./.github/workflows/base-run-bulk-upload.yml"
    needs: ["deploy_all_lambdas"]
    with:
      environment: "development"
      sandbox: ${{ inputs.sandbox_name }}
      combi_settings: "combi300"
      base_branch: ${{ inputs.git_ref }}
      file_count: "3"
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
