name: "SANDBOX: E2e Tests Backend"

run-name: "${{ github.event.inputs.build_branch }} | ${{ github.event.inputs.sandbox }} | ${{ github.event.inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: "Branch to build"
        required: true
        default: "main"
      sandbox:
        description: "Sandbox environment"
        required: true
        default: "ndr"
      environment:
        description: Which environment settings to use?
        required: true
        type: string
        default: development

  workflow_call:
    inputs:
      build_branch:
        required: true
        type: string
      sandbox:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      AWS_ASSUME_ROLE:
        required: true

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  services-e2etest:
    uses: ./.github/workflows/base-e2e-backendtest.yml
    with:
      build_branch: ${{ inputs.build_branch }}
      environment: ${{ inputs.environment }}
      sandbox: ${{ inputs.sandbox }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  services-fhir-api-e2etest:
    uses: ./.github/workflows/base-e2e-fhir-backendtest.yml
    with:
      build_branch: ${{ inputs.build_branch }}
      environment: ${{ inputs.environment }}
      sandbox: ${{ inputs.sandbox }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  services-mns-e2etest:
    uses: ./.github/workflows/base-e2e-mns.yml
    with:
      build_branch: ${{ inputs.build_branch }}
      environment: ${{ inputs.environment }}
      sandbox: ${{ inputs.sandbox }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
