# .github/workflows/terraform-dev
name: "SANDBOX: E2e Tests Backend"

on:
  workflow_dispatch:
    inputs:
      build_branch:
        description: "Branch to build"
        required: true
        default: "main"
      sandbox:
        description: "Sandbox environment"
        required: true
        default: "ndr"

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  services-e2etest:
    uses: ./.github/workflows/base-e2e-backendtest.yml
    with:
      build_branch: ${{ inputs.build_branch }}
      environment: development
      sandbox: ${{ inputs.sandbox }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
  services-fhir-api-e2etest:
    uses: ./.github/workflows/base-e2e-fhir-backendtest.yml
    with:
      build_branch: ${{ inputs.build_branch }}
      environment: development
      sandbox: ${{ inputs.sandbox }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}


  notify-slack:
    runs-on: ubuntu-latest
    needs: [services-e2etest, services-fhir-api-e2etest]
    if: always()
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-skip-session-tagging: true
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true
          
      - name: Get SSM parameters from SSM
        id: ssm-parameters
        run: | 
          slack_bot_token=$(aws ssm get-parameter --name "/ndr/alerting/slack/bot_token" --with-decryption --query "Parameter.Value" --output text)
          echo "::add-mask::$slack_bot_token"
          echo "SLACK_BOT_TOKEN=$slack_bot_token" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # Version v2.1.1
        env:
          SLACK_BOT_TOKEN: ${{ env.SLACK_BOT_TOKEN }}
        with:
          method: chat.postMessage
          token: $SLACK_BOT_TOKEN
          payload: |
            channel: ${{ vars.ALERTS_SLACK_CHANNEL_ID }}
            text: "Workflow has run"

