name: PR Checks & Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body for unchecked checkboxes
        uses: actions-ecosystem/action-checklist@main
        with:
          checklist: ${{ github.event.pull_request.body }}
